services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    entrypoint: wait-for -t 30 app:3000 -- /docker-entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:8080"
    networks:
      - desafio-nginx-nodejs

  app:
    build:
      context: node
    container_name: app
    entrypoint: wait-for database:3306 -- docker-entrypoint.sh
    command: node src/index.js
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=nodedb
      - DB_USER=root
      - DB_PASS=root
    volumes:
      - "./node:/usr/node/app"
    networks:
      - desafio-nginx-nodejs
  
  database:
    image: mysql:lts
    container_name: database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    volumes:
      - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - desafio-nginx-nodejs
networks:
  desafio-nginx-nodejs:
    driver: bridge